name: kgo-test

on:
  push:
    tags:
      - v*
    branches:
      - master
      - release
  pull_request:
    branches: [ master ]

jobs:
  lint:
    strategy:
      matrix:
        go-version: [ 1.14.x, 1.15.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --issues-exit-code=0 --timeout=5m
